package com.rubinho.vkproxy.model;

public enum Role {
    ROLE_ADMIN,
    ROLE_UNVERIFIED_USER,
    ROLE_VERIFIED_USER,
    ROLE_POSTS,
    ROLE_USERS,
    ROLE_ALBUMS,
    ROLE_BANNED,
    ROLE_POSTS_VIEWER,
    ROLE_POSTS_EDITOR,
    ROLE_USERS_VIEWER,
    ROLE_USERS_EDITOR,
    ROLE_ALBUMS_VIEWER,
    ROLE_ALBUMS_EDITOR

}
